version: '3.9'

services:
  backend:
    build: ./backend
    container_name: aulascurzas_backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: aulascurzas_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: aulascurzas_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
